blog/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from .views import Home,\
    PostDetail,\
    CreatePost,\
    UpdatePost,\
    PostDelete,\
    PostCategory,\
    UserCategory



app_name = 'blog'

urlpatterns = [
    path('',Home.as_view(),name='home_view'),
    path('<slug:slug>/',PostDetail.as_view(),name='postdetail'),
    path('<slug:slug>/update/',UpdatePost.as_view(),name='post_update'),
    path('category/<int:pk>/',PostCategory.as_view(),name='post_by_category'),
    path('user/<int:pk>/',UserCategory.as_view(),name='post_by_user'),
    path('<slug:slug>/delete/',PostDelete.as_view(),name='article-delete'),
]

django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from blog.views import Home,Dashboard,CreatePost

urlpatterns = [
    path('login',auth_views.LoginView.as_view(template_name='blog/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(),name='logout'),
    path('',Home.as_view(),name='home_view'),
    path('dashboard',Dashboard.as_view(),name='dashboard'),
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('post/create/',CreatePost.as_view(), name='add_post'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import  slugify
from django.db.models.signals import pre_save # right before the model save we gonna do something


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    creator = models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('post_by_category', args=[self.name])

#Post.objects.all()
#Post.objects.create(user=user,title="some title")
class PostManager(models.Manager):
    def active(self,*args,**kwargs):
        #Post.objects.all() = super(PostManager,self).all()
        return super(PostManager,self).filter(draft=False).filter(published__lte=timezone.now())



class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,null=True,blank=True)
    content = models.TextField()
    image = models.ImageField(null=True,blank=True,upload_to='photos/%Y/%m/%d/')
    pub_date = models.DateTimeField(auto_now_add=True)
    view_count = models.PositiveIntegerField(default=0)
    author = models.ForeignKey(User,on_delete=models.CASCADE) #on_delete is required argument for ForeignKey, you should add it for all ForeignKey fields:
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    draft = models.BooleanField(default=False)
    published = models.DateField(auto_now=False,auto_now_add=False,default=timezone.now())

    objects = PostManager() # here the attribute objects name is just an arbitrary variable by convention we used this name

    def __str__(self): #to return a hard coded string
        return self.title

    def get_absolute_url(self): # to provide a link to a particular object or want to display that object's specific URL (if it has one) to the user
        return reverse('blog:postdetail', kwargs={'slug': self.slug})



class Comment(models.Model):
    content = models.TextField()
    by = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)


# def create_slug(instance, new_slug=None): # here instance is the object of a class which we will use in our function
#     slug = slugify(instance.title)
#     if new_slug is not None:
#         slug = new_slug
#     qs = Post.objects.filter(slug=slug).order_by("-id")
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" %(slug, qs.first().id)
#         return create_slug(instance, new_slug=new_slug)
#     return slug



from .utils import unique_slug_generator

def pre_save_post_receiver(sender, instance, *args, **kwargs): # to make sure this function send every time when we create title or slug we need a sender signal to do so
    if not instance.slug: # if there is no slug present
        #instance.slug = create_slug(instance)
        instance.slug = unique_slug_generator(instance)



pre_save.connect(pre_save_post_receiver, sender=Post) # by signal pre save will run the function every time a model is created

blog/forms.py
from django import forms
from .models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','author','category','content','image','draft','published')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404,reverse
from django.views import View
from django.views.generic import ListView,DetailView,\
    CreateView,UpdateView,DeleteView,FormView #Generic editing views for editing content


from urllib.parse import quote_plus  # turns the url string into share string
from .models import Post,Comment,Category,User
from .forms import PostForm,CommentForm
from django.utils import timezone
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# class based view for Home

class Home(ListView): # listview - return list of object
    model = Post # The model that this view will display data for
    template_name = 'blog/home.html'
    context_object_name = 'posts' # Designates the name of the variable to use in the context.
    ordering = 'pub_date'
    paginate_by = 3



    def get_queryset(self): # here we will override this method to show only the post that is published not saved as draft
        # for search
        query = self.request.GET.get('q')
        if query:
            return Post.objects.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(author__first_name__icontains=query) |
                Q(author__last_name__icontains=query)
            ).distinct()
        #return Post.objects.filter(published__lte=timezone.now())
        if self.request.user.is_superuser:
            return Post.objects.all()
        else:
            return Post.objects.filter(published__lte=timezone.now())




#views for displaying individual post
class PostDisplay(DetailView): # detailview return single object
    model = Post

    def get_object(self, queryset=None): # Returns the single object that this view will display.
        # now create a variable which will call the superclass to
        object = super(PostDisplay,self).get_object()#call the super() so as not to loose other functionalities offered by the original method.
        object.view_count += 1
        object.save()
        return object


   # """Insert and update the comments and form into the context dict."""
    def get_context_data(self, **kwargs): # show the comments of the corrosponding content
        # get the existing context from our superclass.
        context = super(PostDisplay, self).get_context_data(**kwargs)
        # """Insert all the corresponding comments of particular post into the context dict."""
        context['comments']= Comment.objects.filter(post=self.get_object()) # we added the comments into the context--
        context['form'] = CommentForm # """Insert the CommentForm into the context dict."""
        slug = self.kwargs.get(self.slug_url_kwarg)
        instance = get_object_or_404(Post,slug=slug)
        share_string = quote_plus(instance.content) # by share string we able to share our content
        context['share_string']=share_string
        return context


@method_decorator(login_required(login_url='login'),name='dispatch')
class PostComments(FormView): # to publish comment-  A view that displays a form. On error, redisplays the form with
    # validation errors; on success, redirects to a new URL.
    form_class = CommentForm
    template_name = 'blog/post_detail.html'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse which will need a success url as an argument.
        form.instance.by = self.request.user # the logged in user 'by' is the attribute of the Comment model class - by whom the comment will published
        post = Post.objects.get(slug=self.kwargs['slug']) # get the current post
        form.instance.post = post
        form.save() # """If the form is valid, save the associated model."""
        return super(PostComments,self).form_valid(form)

    def get_success_url(self):
        return reverse('blog:postdetail',kwargs={'slug':self.kwargs['slug']})

# Now display the detail post for browsers which only accept GET and POST for now.
class PostDetail(View):
    def get(self,request,*args,**kwargs): # FOR display the POST
        view = PostDisplay.as_view()
        return view(request,*args,**kwargs)

    def post(self,request,*args,**kwargs): # FOR display the post with comment form
        view = PostComments.as_view()
        return view(request,*args,**kwargs)





@method_decorator(login_required(login_url='login'),name='dispatch')
class Dashboard(View):
    def get(self,request,*args,**kwargs):
        view = Home.as_view(
            template_name = 'blog/admin_page.html',
            paginate_by = 4
        )
        return view(request,*args,**kwargs)

class UpdatePost(UpdateView):
    model = Post
    #form_class = PostForm
    fields = ('title', 'category', 'author', 'content', 'image','published','draft')
    template_name_suffix = '_update_form'

    def get_object(self): #get_object method of Django's SingleObjectMixin class.
        slug = self.kwargs.get('slug')  # look kwargs id in the urls  instead of default pk
        return get_object_or_404(Post, slug=slug)



class PostDelete(DeleteView): # View for deleting an object retrieved with self.get_object()
    #template_name = 'blog/article_delete.html'
    model = Post

    def get_object(self):
        slug = self.kwargs.get('slug')  # look kwargs slug in the urls  instead of default pk
        return get_object_or_404(Post, slug=slug)

    def get_success_url(self):
        return reverse('blog:home_view')

class PostCategory(ListView):
    model = Post
    template_name = 'blog/post_category.html'
    paginate_by = 3


    def get_queryset(self):#Returns the queryset that will be used to retrieve the object that this view will display.
        self.category = get_object_or_404(Category,pk=self.kwargs['pk']) # retrieve the individual category by its pk
        return Post.objects.filter(category=self.category) # filter the post with its corresponding category based on unique field- the self.category store the value of pk

    def get_context_data(self, **kwargs): #Returns context data for displaying the object.
        context = super(PostCategory, self).get_context_data(**kwargs)
        context['category']=self.category
        return context

class UserCategory(ListView):
    model = User
    template_name = 'blog/user_category.html'
    paginate_by = 2

    def get_queryset(self):#use get_queryset class method for filtering the list of record return
        # create a variable which will retrieve the pk of the corresponding author of the User model
        self.author = get_object_or_404(User,pk=self.kwargs['pk'])
        # Then return all the post with filter with that particular author which belong to that pk
        return Post.objects.filter(author=self.author)

    # override get_context_data() in order to pass additional context variables to the template
    def get_context_data(self, **kwargs):
        #  # Call the base implementation first to get the context
        context = super(UserCategory, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['author']=self.author # add a variable named "author" to the context
        return context

@method_decorator(login_required(login_url='login'), name='dispatch')
class CreatePost(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    #fields = ('title','category','author','content','image')
    def form_valid(self, form):# If the form is valid, save the associated model."""
        # This method is called when valid form data has been POSTed.
        form.instance.author = self.request.user # instance will get the current data or current form
        self.object= form.save()
        return super(CreatePost,self).form_valid(form) # initiate the super class with method and parameter

blog/templates/blog/admin_page.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin{% endblock %}

{% block content %}

    <div class="blog-table">
        <h2><a href="{% url 'add_post' %}">&#9997 Create New Post</a></h2>
        <table>
            <tr>
                <th>Title</th>
                <th colspan="2">Actions</th>
            </tr>
            {% for post in posts %}
                <tr>
                <td>{{ post.title }}</td>
                <td><a href="{% url 'blog:post_update' post.slug %}">&#9998 Edit</a></td>
                <td><a href="{% url 'blog:article-delete' post.slug %}">&#128465 Delete</a></td>
            </tr>
            {% endfor %}


        </table>
                    
    </div>

    {% include 'blog/pagination_links.html' %}

{% endblock %}

blog/templates/blog/article_delete.html
{% extends 'blog/base.html'%}
{% block breadcrumb %}{{ block.super }} > Admin{% endblock %}
{%block content%}

<form action=" . " method="POST">
    {% csrf_token %}
    <h1>Do you want to delete the post "{{ post.title}}"?</h1>
    <p><input type="submit" value="Yes" /> <a href="../">Cancel</a></p>

</form>

{% endblock %}

blog/templates/blog/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}wakeupbappi{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></script>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></script>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></script>
    
    <nav class="navbar navbar-dark bg-dark justify-content-between">
        <a class="navbar-brand">wakeup_bappi</a>
        <form method="." action="" class="form-inline" >
            <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{{request.GET.q}}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if user.is_authenticated %}
            <p><a href="{% url 'logout' %}">&#128274 Logout</a></p>
        {% else %}
            <p><a href="{% url 'login' %}">&#128275 Login</a></p>
        {% endif %}

        <!--nav class="navbar navbar-light bg-light"-->

<!--/nav-->
    </nav>



    <section class="content-wrapper">
        <div class="breadcrumb">
            <p>{% block breadcrumb %}<a href="{% url 'home_view' %}">Home</a>{% endblock %}</p>
        </div>
        
        {% block content %}

        {% endblock %}
    </section>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}




    {% for post in posts %}
         <div class="blog-item">
        <h2><a href="{% url 'blog:postdetail' post.slug %}">{{ post.title }}</a></h2>
        <div class="info">
            By <span><a href="{% url 'blog:post_by_user' post.category.pk %}">{{ post.author }}</a></span> | In <span><a href="{% url 'blog:post_by_category' post.category.pk %}">{{ post.category }}</a></span> | On <span>{{ post.pub_date }}</span> | &#x1f441 <span>{{ post.view_count }}</span>
        </div>
        <p>
              {{ post.content|truncatewords:30 }}
        </p>
    </div>
    {% empty %}
        <div>
            <h3>There is no post yet.</h3>
        </div>
    {% endfor %}




    {% include 'blog/pagination_links.html' %}

{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{% endblock %}

{% block content %}

   <!--
   > <div class="form login-form">
        <form action=" . " method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}


            <p><input type="submit" value="Login"></p> 
        </form>
    </div> -->
<!DOCTYPE html>
<html>
<style>
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}
input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}
input[type=submit]:hover {
    background-color: #45a049;
}
div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}
</style>
<body>

<div>
  <form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.username.label_tag }}
    {{ form.username }}

    {{ form.password.label_tag }}
    {{ form.password }}

    {{ form.errors }}

    <input type="submit" value="Login">
  </form>
</div>

</body>
</html>

{% endblock %}

blog/templates/blog/pagination_links.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <!--here the default page_obj is provided by ListView Class -->
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post_category.html
{% extends 'blog/base.html' %}

{% block content %}

    <div>
        <h3>{{ category.name}} Category </h3>
    </div>
    {% for post in post_list %}
         <div class="blog-item">
        <h2><a href="{% url 'blog:postdetail' post.slug %}">{{ post.title }}</a></h2>
        <div class="info">
            By <span><a href="#">{{ post.author }}</a></span> | In <span><a href="#">{{ post.category }}</a></span> | On <span>{{ post.pub_date }}</span> | &#x1f441 <span>{{ post.view_count }}</span>
        </div>
        <p>
              {{ post.content|truncatewords:30 }}
        </p>
    </div>
    {% empty %}
        <div>
            <h3>There is no post yet.</h3>
        </div>
    {% endfor %}




    {% include 'blog/pagination_links.html' %}

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin page > Confirm delete{% endblock %}

{% block content %}
    <div class="form">
        <h2>Are you sure you want to delete the "<b>{{ post.title }}</b>" post?</h2>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            <input type="submit" value="Yes">
        </form>
    </div>
    
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% load static %}

{% block breadcrumb %}{{ block.super }} > {{ post.title }}{% endblock %}

{% block content %}

    <div class="blog-item">
        <h2><a href="{% url 'blog:postdetail' post.slug %}">{{ post.title }}</a></h2>
        <small>{% if post.draft %}
            <span style="color:red">Draft</span>
            {% endif %}{{ post.published }}</small>
        <div class="info">
            By <span><a href="#">{{ post.author }}</a></span> | In <span><a href="#">{{ post.category}}</a></span> | On <span>{{post.pub_date}}</span> | &#x1f441 <span>{{ post.view_count }}</span>
        </div>
        <img src='{{ post.image.url }}' class="img-fluid" alt="Responsive image">
        <p>{{ post.content }}</p>
        <div class="fb-like"></div>
    </div>

<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>

    <div class="form">
        <form action=" . " method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="Submit"></p>
        </form>
    </div>

<div>
    <ul>
        <li>
            <div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-size="small"><a  href="{{ request.build_absolute_uri }}" class="fb-xfbml-parse-ignore">Share</a></div>


<a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}">
Twitter
</a>

<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}'>Google-plus
</a>


<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">
Linkedin</a>


<a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">Reddit
</a>
        </li>
    </ul>
</div>




    <div class="comments-list">
        {% for comment in comments %}
            <div class="comment">
            <img src="{% static 'blog/images/avatar.png' %}" alt="avatar">
            <div class="info">
                <p>{{comment.by}}<span>{{comment.created_on}}</span></p>
                <p>{{comment.content}}</p>
            </div>
        </div>
        {% empty %}
        <!-- If comment_list is empty, then the else clause displays text explaining that there are no books to list.-->
        <div>
            <h3> There are no comments yet</h3>
        </div>
        {% endfor %}

    </div>

{% endblock %}
<!--The view passes the context (detail post) by default as object_list and post aliases; either will work.-->

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin page > New Post{% endblock %}

{% block content %}

    <div class="form">
        <form action=" . " method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            
            <p><input type="submit" value="Submit"></p> 
        </form>
    </div>

{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}

{% block breadcrumb %}{{ block.super }} > Admin page > New Post{% endblock %}

{% block content %}

    <div class="form">
        <form action=" . " method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            
            <p><input type="submit" value="Update"></p>
        </form>
    </div>

{% endblock %}

blog/templates/blog/user_category.html
{% extends 'blog/base.html' %}

{% block content %}

    <div>
        <h3>Post By {{ post.author }}</h3>
    </div>
    {% for post in post_list %}
         <div class="blog-item">
        <h2><a href="{% url 'blog:postdetail' post.slug %}">{{ post.title }}</a></h2>
        <div class="info">
            By <span><a href="#">{{ post.author }}</a></span> | In <span><a href="#">{{ post.category }}</a></span> | On <span>{{ post.pub_date }}</span> | &#x1f441 <span>{{ post.view_count }}</span>
        </div>
        <p>
              {{ post.content|truncatewords:30 }}
        </p>
    </div>
    {% empty %}
        <div>
            <h3>There is no post yet.</h3>
        </div>
    {% endfor %}




    {% include 'blog/pagination_links.html' %}

{% endblock %}